name: docker

on:
    push:
        branches: [ docker ]
        tags:
            - v*

env:
    IMAGE_NAME: central-ui

jobs:
    # Push image to GitHub Packages.
    # See also https://docs.docker.com/docker-hub/builds/
    push:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read

        steps:
            - uses: actions/checkout@v3

            - name: Build API Image
              run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

            - name: Log in to registry
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Push API Image
              run: |
                  IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

                  # Change all uppercase to lowercase
                  IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

                  # Strip git ref prefix from version
                  VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

                  # Strip "v" prefix from tag name
                  [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

                  # Use Docker `latest` tag convention
                  LATEST=false
                  [ $VERSION == "docker" ] && LATEST=true
                  [[ $string != *"alpha"* && $string != *"pre"* ]] && LATEST=true

                  echo IMAGE_ID=$IMAGE_ID
                  echo VERSION=$VERSION
                  [ $VERSION != "docker" ] && docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
                  [ $VERSION != "docker" ] && docker push $IMAGE_ID:$VERSION

                  [ "${LATEST}" == true ] && echo "VERSION=${VERSION}" && docker tag $IMAGE_NAME $IMAGE_ID:latest && docker push $IMAGE_ID:latest

            -   name: Webhook
                uses: distributhor/workflow-webhook@v2
                env:
                    webhook_url: ${{ secrets.WEBHOOK_URL }}
                    webhook_secret: ${{ secrets.WEBHOOK_SECRET }}

